openapi: 3.0.0
info:
  title: WWZ Availability API
  version: '1.0'
  contact:
    name: Raphael Ochsenbein
    email: ro@viu.ch
  description: |-
    Get the availability of a specific place.

    Designs
    Available: https://notch-interactive.invisionapp.com/share/XQWAOCVVM9R#/screens/414949963_M020_Verfu-gbarkeitsgebiet_-_Desktop_-_Verfu-gbar
    Unavailable: https://notch-interactive.invisionapp.com/share/XQWAOCVVM9R#/screens/414949964_M020_Verfu-gbarkeitsgebiet_-_Desktop_-_Nicht_Verfu-gbar
    Unknown: https://notch-interactive.invisionapp.com/share/XQWAOCVVM9R#/screens/414949966_M020_Verfu-gbarkeitsgebiet_-_Desktop_-_Unbekannt
servers:
  - url: 'http://localhost:50000'
  - url: 'http://sappot101.wwz.local:50000'
    description: ''
paths:
  /RESTAdapter/Web/AvailabilityCheck:
    post:
      summary: ''
      operationId: post-RESTAdapter-Web-AvailabilityCheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityStatus'
components:
  schemas:
    Place:
      title: Place
      type: object
      properties:
        Strasse:
          type: string
          example: Albisstrasse
        Hausnummer:
          type: string
          example: '20'
        PLZ:
          type: string
          example: '6340'
        Ort:
          type: string
          example: Baar
        Land:
          type: string
          example: CH
          description: iso 3166-1 alpha-2
      description: The location / place for which the availability is requested.
    AvailabilityStatus:
      title: AvailabilityStatus
      type: object
      properties:
        Objekt:
          $ref: '#/components/schemas/PlaceDetail'
        Nachricht:
          $ref: '#/components/schemas/Message'
    PlaceDetail:
      title: PlaceDetail
      type: object
      properties:
        Sparte:
          type: string
          example: '02'
        Hausanschluss:
          type: string
          example: '70000106'
        Objektart:
          type: string
          example: G_HA
        Status:
          type: string
          example: I0100
    Message:
      title: Message
      type: object
      properties:
        Text:
          type: string
          example: Hausanschluss gefunden.
        Typ:
          type: string
          example: S
  securitySchemes: {}
